### PR TITLE
Add SuperDiff::Configuration#color_enabled=

### PR DESCRIPTION
**Pull request by knu**
Currently, you need to use merge!(), which doesn't look pretty.

```ruby
SuperDiff.configure do |config|
  config.merge!(color_enabled: false) if ENV['CIRCLECI'] # because the log is not colorized when it is too huge
end
```

### CODE REVIEW

**Comment by morissetcl** [comment]
The following config should works ?
```
SuperDiff::Csi.color_enabled = false if ENV["CI"]
```

**Comment by mcmire** [comment]
@morissetcl Yes, that is a quick fix for now.

@knu Sorry I didn't see this when you initially created it. Would you mind repushing your branch? For some reason none of the GitHub Actions ran. You might try running `git rebase master` to refresh the commit you have and then force-pushing.

**Comment by knu** [comment]
I have recreated the commit and force-pushed.  Does this work?

**Comment by mcmire** [comment]
Yup! Running CI now.

**Comment by petergoldstein** [comment]
@knu You probably need to rebase against `main` at this point.

**Comment by mcmire** [comment]
Sorry for not getting to this sooner @knu, thanks for the PR!

**Comment by sshaw** [comment]
Shouldn't this check be changed: https://github.com/mcmire/super_diff/blob/fb6718a2b60bc8135424295cc069a4b984983f77/lib/super_diff/configuration.rb#L146

if `ENV["CI"] == "true"` we do not want color, right?

**Comment by sshaw** [comment]
Nevertheless, can we get a release for the `config.color_enabled` addition? :)

**Pull request merged**
