### PR TITLE
feat: date like objects support

### LINKED ISSUE #182: Failed Assertions on Date Instances Do Not Output a Diff
0.9.0, running under Rails: 
```rb
expect(Date.new(2020, 2, 1)).to eq Date.new(2020, 2, 2)
```

Results in: 
```
  Expected #<Date:0x0000000124fed510> to eq #<Date:0x0000000124fed470>.

       Diff:

       ┌ (Key) ──────────────────────────┐
       │ ‹-› in expected, not in actual  │
       │ ‹+› in actual, not in expected  │
       │ ‹ › in both expected and actual │
       └─────────────────────────────────┘

         #<Date:0x0000000124fed510 {
         }>
```

If it is changed `Time`:

```rb
expect(Date.new(2020, 2, 1).to_time).to eq Date.new(2020, 2, 2).to_time
```

Then a diff is output.

### PR DESCRIPTION
**Pull request by fizvlad**
Closes #182 

Tbh, I just went through appearances of `/(TimeLike|time_like)/` and created similar logic for date like objects :D

I'm really hesitant about whether `DateTime` objects should be considered `date_like` (although ActiveSupport defines `DateTime#acts_like_date?`). Since `Date` and `DateTime` are never equal, `expect(Date.new(2020, 1, 1)).to eq(DateTime.new(2020, 1, 1))` will result in a confusing diff (see the [spec/support/shared_examples/active_support.rb](https://github.com/mcmire/super_diff/pull/198/files#diff-4076c9b6c197bc5a4b90327f7efc27f9a0bc5f40ec98dfe94adf9c08f103a269R103-R143))

### CODE REVIEW

**Comment by fizvlad** [comment]
@mcmire, could you take a look?

**Comment by mcmire** [comment]
Hey @fizvlad! Thanks for the PR. I've looked over it and nothing stands out, but haven't had time to play with it yet.

About the confusing diff — is there anything you feel like should happen differently there?

**Comment by fizvlad** [comment]
> About the confusing diff — is there anything you feel like should happen differently there?

I'm only concerned about diff making it feel like `day: 14` instead of `day: 31` is the only problem, while classes of `expected` and `actual` also matter. Maybe highlighting that objects got different classes would make diff better. As a user I probably wouldn't even notice this behavior, so I'm totally fine with not doing any changes :D

Current output:
```
       Actual output:

       ---START----------------------------------------------------------------
       F

       Failures:

         1) test passes
            Failure/Error: expect(expected).to eq(actual)

              Expected #<Date 2023-10-14> to eq #<DateTime 2023-10-31 18:22:26 +00:00 (+00:00)>.

              Diff:

              ┌ (Key) ──────────────────────────┐
              │ ‹-› in expected, not in actual  │
              │ ‹+› in actual, not in expected  │
              │ ‹ › in both expected and actual │
              └─────────────────────────────────┘

                #<Date {
                  year: 2023,
                  month: 10,
              -   day: 31
              +   day: 14
                }>
            # ./lib/super_diff/rspec/monkey_patches.rb:43:in `handle_failure'
            # ./tmp/integration_spec.rb:16:in `block (2 levels) in <top (required)>'

       Finished in 0.02233 seconds (files took 0.575 seconds to load)
       1 example, 1 failure

       Failed examples:

       rspec ./tmp/integration_spec.rb:13 # test passes
       ---END------------------------------------------------------------------
```

**Comment by fizvlad** [comment]
Rebased the branch to resolve merge conflicts

**Comment by fizvlad** [comment]
Specs with `no_rails` were failing since `date` is not required by default (resolved by adding `require "date"`) and `DateTime` only have special inspect with ActiveSupport (moved specs to active_support folfer)

**Comment by fizvlad** [comment]
Hey, @mcmire ! Could you take another look?

**Comment by mcmire** [comment]
Hey @fizvlad! Sorry for the long delay on this. I think I can fix that diff issue you mentioned but the rest of this seemed fine! Thanks again for the PR.

**Comment by mcmire** [comment]
This feature has been included in [v0.11.0](https://github.com/mcmire/super_diff/releases/tag/v0.11.0). Thanks again!

**Pull request merged**
