### PR TITLE
WIP: Ruby2.7 support

### PR DESCRIPTION
**Pull request by numbata**
This PR suppress some Ruby2.7 warnings.

### CODE REVIEW

**Comment by mcmire** [comment]
Hey, thanks for doing this! Did you want to leave your commits as-is or squash them? Just making sure before I merge.

**Comment by mcmire** [comment]
Also it looks like @aried3r got to this first so I merged in their PR — hope that's okay. I'm assuming that the other changes here have to do with upgrading to Ruby 2.7, though? Or are they to satisfy Rubocop?

**Comment by numbata** [comment]
> Also it looks like @aried3r got to this first so I merged in their PR — hope that's okay.

Sure 👍 

> I'm assuming that the other changes here have to do with upgrading to Ruby 2.7, though? Or are they to satisfy Rubocop?

Yeap, Ruby 2.7 shows some warnings right now. "warning: Using the last argument as keyword parameters is deprecated" for example. So, my changes are around suppressing that deprications and warnings.

> Did you want to leave your commits as-is or squash them? Just making sure before I merge.

I'll do it. Just want to fix couple of warnings before that.

**Comment by mcmire** [comment]
Hey, just checking here. Was there any more work you wanted to do on this?

**Comment by numbata** [comment]
@mcmire thank you for your "ping" :) I'll check and back with results tomorrow.

**Comment by numbata** [comment]
@mcmire So, I did fix what I can. Other warnings are coming from the "rspec-expectations" and the "attr_extras" gems.

**Comment by mcmire** [comment]
Okay! Thanks so much for doing this!

**Pull request merged**
