### PR TITLE
Test with Rails 6.1

### PR DESCRIPTION
**Pull request by aried3r**
Adds testing with Rails 6.1. With rspec <3.10 I had over 263 test failures so I excluded it from the matrix and Appraisal.

### CODE REVIEW

**Comment by mcmire** [comment]
Thanks for doing this. Is RSpec < 3.10 not compatible with Rails 6.1? If it's intended to be compatible, is that something you think should be addressed? Or did you just want to make sure that _something_ around Rails 6.1 integration was added to the test suite?

**Comment by aried3r** [comment]
Hey!

I am not a 100% sure how the `rspec` meta-gem relates to it. However it appears to me that official Rails 6.1 support hit `rspec-rails` in [5.0.0](https://github.com/rspec/rspec-rails/blob/v5.0.1/Changelog.md#500--2021-03-09), with some fixes being in previous versions.

In turn, this version seems to [request `rspec-*` of 3.10 or above](https://github.com/rspec/rspec-rails/blob/v5.0.1/rspec-rails.gemspec#L42-L57).

I have no data on this, but my assumption is that users of Rails 6.1 which requires Ruby 2.5 have a reasonably up-to-date setup and will be using the `rspec-rails` version that has official support for it.

Do you think this is a reasonable approach for this gem?

Edit: I forgot to answer your questions directly.

> Is RSpec < 3.10 not compatible with Rails 6.1? If it's intended to be compatible, is that something you think should be addressed? 

I don't think it should be addressed, see explanation above.

> Or did you just want to make sure that _something_ around Rails 6.1 integration was added to the test suite?

Yes 😅

**Comment by aried3r** [comment]
Hey @mcmire! If you're okay with the PR as it is, I'd perhaps also add Rails 7 alpha if you're interested.

**Comment by mcmire** [comment]
Hey @aried3r! So sorry for not getting to this PR until now. I've been working with @petergoldstein on some updates to the CI matrix as well and he incorporated your PR into his. I made sure you were credited on the commit. Hope that's okay!

**Comment by aried3r** [comment]
Absolutely, thank you!

**Pull request closed without merging**
