### PR TITLE
#97 - Fixup match array as string

### PR DESCRIPTION
**Pull request by guiferrpereira**
Corrects issue #97

### CODE REVIEW

**Comment by mcmire** [comment]
Hi @guiferrpereira. Thanks for this PR. Is it possible for you to add a new context and test to this file https://github.com/mcmire/super_diff/blob/master/spec/integration/rspec/match_array_matcher_spec.rb which makes sure that this isn't an issue going forward?

**Comment by guiferrpereira** [comment]
sure

**Comment by guiferrpereira** [comment]
@mcmire specs added

**Comment by mcmire** [comment]
Okay! Thanks so much!

**Comment by guiferrpereira** [comment]
@mcmire can you create the 0.5.3 release please? thanks

**Comment by mcmire** [comment]
@guiferrpereira Yes, thanks for the reminder. 0.5.3 is now available with this change.

**Pull request merged**
